"""BFS-optimal V* enumerator for the 2x2 cube.

The 2x2 has 8 corners with 3-bit positions and 2-bit orientations,
giving 8! × 3^7 = 88,179,840 distinct face-turn-reachable configurations
in our 24-sticker representation. Modulo the 24-element whole-cube
rotation group (which preserves cost-to-go from solved), there are
exactly 3,674,160 canonical states — the standard 2x2 reachability count.

This module BFS-enumerates all 3,674,160 canonical states and stores
their minimum-QTM-distance to solved (0..14; 14 is God's Number for
2x2 in QTM. 11 — sometimes quoted as "2x2 God's Number" — is the
HTM result, but our move set is QTM-only so 14 is the relevant
diameter). The result is cached to disk on first compute (~30s wall
on M4 Max); subsequent loads are sub-second.

Canonicalization: each state has 24 whole-cube-rotation siblings; we
pick the lex-minimum over the 24-orbit as the canonical representative.
The 24 cube rotations are generated by composing U·D' (90° rotation
around U/D axis) and R·L' (90° around L/R axis), expressed as sticker
permutations using the M2 move tables — no oracle dependency at runtime.

Public API:
- ``compute_v_star_2x2(spec, *, max_depth, cache_path, verbose)``
- ``canonicalize_state(state)`` / ``canonicalize_states_batch(states)``
- ``lookup_v_star(state, v_star)`` / ``lookup_v_star_batch(states, v_star)``
- ``save_v_star(v_star, path)`` / ``load_v_star(path)``

Used by training (M5 acceptance eval, ground-truth MAE) and search (M6,
verify beam returns BFS-optimal solution lengths).
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
import torch

from rubik.cube.env import MOVE_PERM_2X2
from rubik.cube.spec import CubeSpec

_MOVE_PERM_NP: np.ndarray = MOVE_PERM_2X2.numpy().astype(np.int64)


def _generate_cube_rotation_perms() -> np.ndarray:
    """24 whole-cube rotations as sticker permutations, shape (24, 24).

    Generators: Y_rot = U·D' (90° CW around vertical axis) and
    X_rot = R·L' (90° CW around L-R axis). BFS the closure under
    composition until 24 distinct elements are found.

    A permutation P acts on a state s by ``s_new = s[P]`` — composing
    "apply A then apply B" yields ``A[B]`` since
    ``s_new[i] = s[A[B[i]]] = (s[A])[B][i]``.
    """
    perm_u = _MOVE_PERM_NP[0]
    perm_d_inv = _MOVE_PERM_NP[11]
    perm_r = _MOVE_PERM_NP[6]
    perm_l_inv = _MOVE_PERM_NP[3]

    y_rot = perm_u[perm_d_inv]
    x_rot = perm_r[perm_l_inv]

    identity = np.arange(24, dtype=np.int64)
    rotations: dict[bytes, np.ndarray] = {identity.tobytes(): identity}
    frontier = [identity]
    while frontier:
        new_frontier: list[np.ndarray] = []
        for r in frontier:
            for g in (y_rot, x_rot):
                composed = r[g]
                key = composed.tobytes()
                if key not in rotations:
                    rotations[key] = composed
                    new_frontier.append(composed)
        frontier = new_frontier

    if len(rotations) != 24:
        raise RuntimeError(
            f"cube rotation group should have 24 elements; got {len(rotations)}"
        )
    return np.stack(list(rotations.values()))


_CUBE_ROT_PERM: np.ndarray = _generate_cube_rotation_perms()


def canonicalize_state(state: np.ndarray | torch.Tensor) -> np.ndarray:
    """Return the lex-minimum among the 24 whole-cube rotations of state.

    Input: any (24,)-shape int8/int64 array or a torch tensor.
    Output: (24,) int8 — the canonical representative of state's orbit.
    """
    if isinstance(state, torch.Tensor):
        state = state.detach().cpu().numpy()
    if state.shape != (24,):
        raise ValueError(f"expected (24,) state; got shape {state.shape}")
    if state.dtype != np.int8:
        state = state.astype(np.int8)
    candidates = state[_CUBE_ROT_PERM]  # (24, 24) int8
    # 'S24' byte-string dtype is lex-orderable; np.void isn't.
    # Requires C-contiguous; np.ascontiguousarray is a no-op when already so.
    byte_view = np.ascontiguousarray(candidates).view("S24")
    min_idx = int(byte_view.argmin())
    return candidates[min_idx]


def canonicalize_states_batch(states: np.ndarray | torch.Tensor) -> np.ndarray:
    """Vectorized lex-min canonicalization for shape (B, 24). Returns int8."""
    if isinstance(states, torch.Tensor):
        states = states.detach().cpu().numpy()
    if states.ndim != 2 or states.shape[1] != 24:
        raise ValueError(f"expected (B, 24) states; got shape {states.shape}")
    if states.dtype != np.int8:
        states = states.astype(np.int8)
    candidates = states[:, _CUBE_ROT_PERM]  # (B, 24, 24) int8
    byte_view = np.ascontiguousarray(candidates).view("S24")  # (B, 24, 1) bytes
    min_idx = byte_view.reshape(byte_view.shape[0], -1).argmin(axis=1)  # (B,)
    return np.take_along_axis(candidates, min_idx[:, None, None], axis=1).squeeze(1)


def compute_v_star_2x2(
    spec: CubeSpec,
    *,
    max_depth: int | None = None,
    cache_path: Path | None = None,
    verbose: bool = False,
) -> dict[bytes, int]:
    """BFS the canonical 2x2 state space; map each state → optimal QTM distance.

    Args:
        spec: must be the 2x2 spec — V* enumeration is exclusive to 2x2.
        max_depth: if given, stop BFS at this depth (useful for fast tests).
                   None = full BFS to God's Number (~30s wall on M4 Max).
        cache_path: optional .npz path. If exists, load instead of recomputing.
                    If given and we computed fresh, save the result.
        verbose: print per-layer progress.

    Returns:
        dict[bytes, int] mapping packed canonical-state bytes → optimal depth.
    """
    if cache_path is not None and cache_path.exists():
        if verbose:
            print(f"loading V* from {cache_path}")
        return load_v_star(cache_path)

    if spec.name != "2x2":
        raise ValueError(f"V* enumeration only supported for 2x2; got {spec.name!r}")

    solved = spec.solved_state.numpy()
    solved_canon = canonicalize_state(solved)
    visited: dict[bytes, int] = {solved_canon.tobytes(): 0}
    frontier = solved_canon[None, :]  # (1, 24) int8
    depth = 0

    while frontier.shape[0] > 0:
        if max_depth is not None and depth >= max_depth:
            break
        depth += 1
        children = frontier[:, _MOVE_PERM_NP].reshape(-1, 24).astype(np.int8)
        children_canon = canonicalize_states_batch(children)

        new_states_list: list[np.ndarray] = []
        for s in children_canon:
            key = s.tobytes()
            if key not in visited:
                visited[key] = depth
                new_states_list.append(s)

        if not new_states_list:
            break
        frontier = np.stack(new_states_list)

        if verbose:
            print(
                f"depth {depth}: {len(new_states_list)} new states,"
                f" {len(visited)} total"
            )

    if cache_path is not None:
        save_v_star(visited, cache_path)
        if verbose:
            print(f"saved V* to {cache_path}")

    return visited


def save_v_star(v_star: dict[bytes, int], path: Path) -> None:
    """Save V* dict to a compressed npz file."""
    n = len(v_star)
    states = np.empty((n, 24), dtype=np.int8)
    depths = np.empty(n, dtype=np.int8)
    for i, (key, d) in enumerate(v_star.items()):
        states[i] = np.frombuffer(key, dtype=np.int8)
        depths[i] = d
    path.parent.mkdir(parents=True, exist_ok=True)
    np.savez_compressed(path, states=states, depths=depths)


def load_v_star(path: Path) -> dict[bytes, int]:
    """Load V* dict from a compressed npz file."""
    with np.load(path) as data:
        states = data["states"]
        depths = data["depths"]
    return {states[i].tobytes(): int(depths[i]) for i in range(len(states))}


def load_v_star_arrays(path: Path) -> tuple[np.ndarray, np.ndarray]:
    """Load V* as (states, depths) arrays — needed for V*-stratified sampling.

    Returns:
        states: ``(N, 24)`` int8 — canonical-state representatives.
        depths: ``(N,)`` int8 — optimal QTM depth for the corresponding row.
    """
    with np.load(path) as data:
        states = data["states"].copy()
        depths = data["depths"].copy()
    return states, depths


def sample_states_at_v_star(
    states: np.ndarray,
    depths: np.ndarray,
    target_v_star: int,
    n: int,
    *,
    rng: np.random.Generator,
    rotate: bool = False,
) -> np.ndarray:
    """Uniformly sample ``n`` states with ``V*[state] == target_v_star``.

    The V* table stores canonical (lex-min over the 24-rotation orbit)
    representatives. Whole-cube rotations preserve V*, so ``rotate=True`` can
    apply a random rotation per row — useful when a downstream consumer
    cares about the input distribution (e.g. comparing net predictions
    directly).

    **Default is ``rotate=False`` because the solver path
    (``greedy_solve_batch`` / ``beam_solve_batch``) tests ``is_solved``
    against ``spec.solved_state`` exactly — rotated solved states fail
    that equality check, so a rotated V*=k state cannot be recognized as
    solved when it reaches its rotated-solved target.** When using this
    sampler to feed the solver, leave rotation off.

    Args:
        states: ``(N, 24)`` int8 — from ``load_v_star_arrays``.
        depths: ``(N,)`` int — same shape as ``states``.
        target_v_star: the V* depth to sample from. ``0`` is the (lone) solved
            state.
        n: number of states to return.
        rng: numpy random generator (deterministic when seeded).
        rotate: if True, apply a random whole-cube rotation per row before
            returning.

    Returns:
        ``(n, 24)`` int8 array of states. Sampling is with replacement when
        ``n`` exceeds the orbit count at this depth.

    Raises:
        ValueError: if no states have ``V* == target_v_star``.
    """
    if n < 0:
        raise ValueError(f"n must be non-negative; got {n}")
    if n == 0:
        return np.empty((0, 24), dtype=np.int8)
    mask = depths == target_v_star
    if not mask.any():
        raise ValueError(
            f"no states with V*={target_v_star} in the table "
            f"(table covers V* ∈ {{{int(depths.min())}, ..., {int(depths.max())}}})"
        )
    candidate_idx = np.flatnonzero(mask)
    n_candidates = candidate_idx.shape[0]
    replace = n > n_candidates
    chosen_local = rng.choice(n_candidates, size=n, replace=replace)
    chosen = candidate_idx[chosen_local]
    sampled = states[chosen].astype(np.int8, copy=True)

    if rotate:
        rot_idx = rng.integers(0, 24, size=n)
        perms = _CUBE_ROT_PERM[rot_idx]  # (n, 24)
        sampled = np.take_along_axis(sampled, perms, axis=1)

    return sampled


def lookup_v_star(state: np.ndarray | torch.Tensor, v_star: dict[bytes, int]) -> int:
    """Look up the optimal QTM distance for a single state."""
    canon = canonicalize_state(state)
    return v_star[canon.tobytes()]


def lookup_v_star_batch(
    states: np.ndarray | torch.Tensor, v_star: dict[bytes, int]
) -> np.ndarray:
    """Vectorized V* lookup for shape (B, 24). Returns (B,) int8."""
    canon = canonicalize_states_batch(states)
    return np.array([v_star[c.tobytes()] for c in canon], dtype=np.int8)
