"""Codegen: emit web/src/solver/moveTables.ts from MOVE_PERM_3X3.

The TS beam (web/src/solver/beam.ts, M11 Block B) needs the same
sticker-permutation table as the Python env to expand children inside
the browser / Node. Python is the single source of truth — this script
reads ``rubik.cube.env.MOVE_PERM_3X3`` and serializes it as a flat
``Uint8Array`` (12 moves × 54 stickers = 648 bytes inlined, all indices
fit in a byte since 0 ≤ idx < 54).

Idempotent — re-running with no upstream changes produces an identical
file. Drift gate: re-run after touching either the Python move table or
this script; the diff is the drift.

Usage:
    uv run python scripts/codegen_move_table_3x3.py
"""

from __future__ import annotations

from pathlib import Path

from rubik.cube.env import MOVE_PERM_3X3
from rubik.cube.spec import CUBE_3X3
from rubik.notation.moves import MOVE_STRINGS

REPO_ROOT = Path(__file__).resolve().parent.parent
OUTPUT_PATH = REPO_ROOT / "web" / "src" / "solver" / "moveTables.ts"


def render_ts() -> str:
    n_moves = CUBE_3X3.n_moves
    n_stickers = CUBE_3X3.n_stickers
    assert MOVE_PERM_3X3.shape == (n_moves, n_stickers), (
        f"unexpected MOVE_PERM_3X3 shape {tuple(MOVE_PERM_3X3.shape)}"
    )
    assert int(MOVE_PERM_3X3.max()) < 256, "perm values must fit in a byte"
    assert int(MOVE_PERM_3X3.min()) >= 0, "perm values must be non-negative"

    rows = MOVE_PERM_3X3.tolist()
    lines: list[str] = []
    for m, row in enumerate(rows):
        nums = ", ".join(str(x) for x in row)
        # Match the comment style of MOVE_PERM_3X3 ("// 0: U", "// 1: U'", ...).
        lines.append(f"  {nums}, // {m}: {MOVE_STRINGS[m]}")
    body = "\n".join(lines)

    header = (
        "// GENERATED by scripts/codegen_move_table_3x3.py"
        " — do not edit by hand.\n"
        "// Mirror of MOVE_PERM_3X3 from src/rubik/cube/env.py."
        " Re-run after changes.\n"
        "//\n"
        "// movePerm3x3[m * 54 + i] = source sticker slot for slot i"
        " after move m.\n"
        "// Apply via: new_state[i] = old_state[movePerm3x3[m * 54 + i]].\n"
    )

    return (
        f"{header}\n"
        f"export const N_MOVES_3X3 = {n_moves};\n"
        f"export const N_STICKERS_3X3 = {n_stickers};\n"
        f"\n"
        f"export const movePerm3x3: Uint8Array = new Uint8Array([\n"
        f"{body}\n"
        f"]);\n"
    )


def main() -> None:
    new_content = render_ts()
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(new_content)
    n_bytes = CUBE_3X3.n_moves * CUBE_3X3.n_stickers
    print(f"wrote: {OUTPUT_PATH} ({n_bytes} bytes inlined)")


if __name__ == "__main__":
    main()
