"""Fast tensor cube — production code path for env / training / search.

State is a flat sticker tensor of shape `(spec.n_stickers,)` (single) or
`(B, spec.n_stickers)` (batched), dtype `int8`. Move tables are static
sticker permutations snapshotted from the M1 oracle (see
`visuals/scripts/generate_move_perm_2x2.py`); this module never imports
the oracle at runtime. Drift is caught by `test_move_perm_matches_oracle`.

Functions are device-agnostic and dtype-preserving — MPS tuning is M4.
"""

import torch

from rubik.cube.spec import CubeSpec

# Snapshot generated by visuals/scripts/generate_move_perm_2x2.py.
# perm[move_idx, i] = source sticker position of slot i after the move.
# Apply via torch.gather(states, -1, perm[move_idxs]).
MOVE_PERM_2X2 = torch.tensor(
    (
        (2, 0, 3, 1, 8, 9, 6, 7, 12, 13, 10, 11, 16, 17, 14, 15, 4, 5, 18, 19, 20, 21, 22, 23),  # 0: U
        (1, 3, 0, 2, 16, 17, 6, 7, 4, 5, 10, 11, 8, 9, 14, 15, 12, 13, 18, 19, 20, 21, 22, 23),  # 1: U'
        (19, 1, 17, 3, 6, 4, 7, 5, 0, 9, 2, 11, 12, 13, 14, 15, 16, 22, 18, 20, 8, 21, 10, 23),  # 2: L
        (8, 1, 10, 3, 5, 7, 4, 6, 20, 9, 22, 11, 12, 13, 14, 15, 16, 2, 18, 0, 19, 21, 17, 23),  # 3: L'
        (0, 1, 7, 5, 4, 20, 6, 21, 10, 8, 11, 9, 2, 13, 3, 15, 16, 17, 18, 19, 14, 12, 22, 23),  # 4: F
        (0, 1, 12, 14, 4, 3, 6, 2, 9, 11, 8, 10, 21, 13, 20, 15, 16, 17, 18, 19, 5, 7, 22, 23),  # 5: F'
        (0, 9, 2, 11, 4, 5, 6, 7, 8, 21, 10, 23, 14, 12, 15, 13, 3, 17, 1, 19, 20, 18, 22, 16),  # 6: R
        (0, 18, 2, 16, 4, 5, 6, 7, 8, 1, 10, 3, 13, 15, 12, 14, 23, 17, 21, 19, 20, 9, 22, 11),  # 7: R'
        (13, 15, 2, 3, 1, 5, 0, 7, 8, 9, 10, 11, 12, 23, 14, 22, 18, 16, 19, 17, 20, 21, 4, 6),  # 8: B
        (6, 4, 2, 3, 22, 5, 23, 7, 8, 9, 10, 11, 12, 0, 14, 1, 17, 19, 16, 18, 20, 21, 15, 13),  # 9: B'
        (0, 1, 2, 3, 4, 5, 18, 19, 8, 9, 6, 7, 12, 13, 10, 11, 16, 17, 14, 15, 22, 20, 23, 21),  # 10: D
        (0, 1, 2, 3, 4, 5, 10, 11, 8, 9, 14, 15, 12, 13, 18, 19, 16, 17, 6, 7, 21, 23, 20, 22),  # 11: D'
    ),
    dtype=torch.int64,
)


# Keyed by spec.name so 3x3 drops in alongside 2x2 in M5 with no code-path change.
_MOVE_PERM: dict[str, torch.Tensor] = {"2x2": MOVE_PERM_2X2}


def _perm_for(spec: CubeSpec) -> torch.Tensor:
    perm = _MOVE_PERM.get(spec.name)
    if perm is None:
        raise ValueError(f"no move-permutation table for spec {spec.name!r}")
    return perm


def apply_moves(
    states: torch.Tensor, move_idxs: torch.Tensor | int, spec: CubeSpec
) -> torch.Tensor:
    """Apply moves to states; preserves device and dtype.

    `states` shape `(S,)` or `(B, S)`. `move_idxs` may be a Python int, a
    0-d tensor (broadcast across the batch / single state), or a 1-d
    tensor of length B (one move per row).
    """
    if states.shape[-1] != spec.n_stickers:
        raise ValueError(
            f"states last dim {states.shape[-1]} does not match"
            f" spec.n_stickers ({spec.n_stickers})"
        )
    perm = _perm_for(spec).to(states.device)

    move_idxs_t = (
        move_idxs
        if isinstance(move_idxs, torch.Tensor)
        else torch.tensor(move_idxs, dtype=torch.int64)
    )
    move_idxs_t = move_idxs_t.to(states.device)
    if move_idxs_t.dtype != torch.int64:
        move_idxs_t = move_idxs_t.to(torch.int64)
    if (move_idxs_t < 0).any() or (move_idxs_t >= spec.n_moves).any():
        raise ValueError(f"move index out of range [0, {spec.n_moves})")

    if move_idxs_t.dim() == 0:
        gathered = perm[move_idxs_t]  # (S,)
        if states.dim() == 1:
            return torch.gather(states, -1, gathered)
        # Broadcast a single move across a batch of states.
        gathered = gathered.unsqueeze(0).expand(states.shape[0], -1)
        return torch.gather(states, -1, gathered)

    if move_idxs_t.dim() == 1:
        if states.dim() != 2:
            raise ValueError(
                "1-d move_idxs requires 2-d states (B, S);"
                f" got states shape {tuple(states.shape)}"
            )
        if move_idxs_t.shape[0] != states.shape[0]:
            raise ValueError(
                f"move_idxs length {move_idxs_t.shape[0]} != batch"
                f" size {states.shape[0]}"
            )
        return torch.gather(states, -1, perm[move_idxs_t])

    raise ValueError(f"move_idxs must be 0-d or 1-d; got {move_idxs_t.dim()}-d")


def is_solved(states: torch.Tensor, spec: CubeSpec) -> torch.Tensor:
    """Return scalar bool for `(S,)` input, shape `(B,)` for `(B, S)`."""
    if states.shape[-1] != spec.n_stickers:
        raise ValueError(
            f"states last dim {states.shape[-1]} does not match"
            f" spec.n_stickers ({spec.n_stickers})"
        )
    target = spec.solved_state.to(device=states.device, dtype=states.dtype)
    if states.dim() == 1:
        return (states == target).all()
    return (states == target).all(dim=-1)
