"""Fast tensor cube — production code path for env / training / search.

State is a flat sticker tensor of shape `(spec.n_stickers,)` (single) or
`(B, spec.n_stickers)` (batched), dtype `int8`. Move tables are static
sticker permutations snapshotted from the M1 oracle (see
`scripts/move_perm_from_oracle_2x2.py`); this module never imports
the oracle at runtime. Drift is caught by `test_move_perm_matches_oracle`.

Functions are device-agnostic and dtype-preserving — MPS tuning is M4.
"""

from collections.abc import Sequence

import torch

from rubik.cube.spec import CubeSpec

# Snapshot generated by scripts/move_perm_from_oracle_2x2.py.
# perm[move_idx, i] = source sticker position of slot i after the move.
# Apply via torch.gather(states, -1, perm[move_idxs]).
# Rows are one-line-per-move for scannability; line length is suppressed
# below (24 ints + comma+space don't fit in 88 cols and splitting hurts
# readability of the snapshot). Re-run the generator if any row changes.
# fmt: off
MOVE_PERM_2X2 = torch.tensor(
    (
        (2, 0, 3, 1, 8, 9, 6, 7, 12, 13, 10, 11, 16, 17, 14, 15, 4, 5, 18, 19, 20, 21, 22, 23),  # 0: U   # noqa: E501
        (1, 3, 0, 2, 16, 17, 6, 7, 4, 5, 10, 11, 8, 9, 14, 15, 12, 13, 18, 19, 20, 21, 22, 23),  # 1: U'  # noqa: E501
        (19, 1, 17, 3, 6, 4, 7, 5, 0, 9, 2, 11, 12, 13, 14, 15, 16, 22, 18, 20, 8, 21, 10, 23),  # 2: L   # noqa: E501
        (8, 1, 10, 3, 5, 7, 4, 6, 20, 9, 22, 11, 12, 13, 14, 15, 16, 2, 18, 0, 19, 21, 17, 23),  # 3: L'  # noqa: E501
        (0, 1, 7, 5, 4, 20, 6, 21, 10, 8, 11, 9, 2, 13, 3, 15, 16, 17, 18, 19, 14, 12, 22, 23),  # 4: F   # noqa: E501
        (0, 1, 12, 14, 4, 3, 6, 2, 9, 11, 8, 10, 21, 13, 20, 15, 16, 17, 18, 19, 5, 7, 22, 23),  # 5: F'  # noqa: E501
        (0, 9, 2, 11, 4, 5, 6, 7, 8, 21, 10, 23, 14, 12, 15, 13, 3, 17, 1, 19, 20, 18, 22, 16),  # 6: R   # noqa: E501
        (0, 18, 2, 16, 4, 5, 6, 7, 8, 1, 10, 3, 13, 15, 12, 14, 23, 17, 21, 19, 20, 9, 22, 11),  # 7: R'  # noqa: E501
        (13, 15, 2, 3, 1, 5, 0, 7, 8, 9, 10, 11, 12, 23, 14, 22, 18, 16, 19, 17, 20, 21, 4, 6),  # 8: B   # noqa: E501
        (6, 4, 2, 3, 22, 5, 23, 7, 8, 9, 10, 11, 12, 0, 14, 1, 17, 19, 16, 18, 20, 21, 15, 13),  # 9: B'  # noqa: E501
        (0, 1, 2, 3, 4, 5, 18, 19, 8, 9, 6, 7, 12, 13, 10, 11, 16, 17, 14, 15, 22, 20, 23, 21),  # 10: D  # noqa: E501
        (0, 1, 2, 3, 4, 5, 10, 11, 8, 9, 14, 15, 12, 13, 18, 19, 16, 17, 6, 7, 21, 23, 20, 22),  # 11: D' # noqa: E501
    ),
    dtype=torch.int64,
)
# fmt: on


# Keyed by spec.name so 3x3 drops in alongside 2x2 in M5 with no code-path change.
_MOVE_PERM: dict[str, torch.Tensor] = {"2x2": MOVE_PERM_2X2}


def _perm_for(spec: CubeSpec) -> torch.Tensor:
    perm = _MOVE_PERM.get(spec.name)
    if perm is None:
        raise ValueError(f"no move-permutation table for spec {spec.name!r}")
    return perm


def apply_moves(
    states: torch.Tensor, move_idxs: torch.Tensor | int, spec: CubeSpec
) -> torch.Tensor:
    """Apply moves to states; preserves device and dtype.

    `states` shape `(S,)` or `(B, S)`. `move_idxs` may be a Python int, a
    0-d tensor (broadcast across the batch / single state), or a 1-d
    tensor of length B (one move per row).
    """
    if states.shape[-1] != spec.n_stickers:
        raise ValueError(
            f"states last dim {states.shape[-1]} does not match"
            f" spec.n_stickers ({spec.n_stickers})"
        )
    perm = _perm_for(spec).to(states.device)

    move_idxs_t = (
        move_idxs
        if isinstance(move_idxs, torch.Tensor)
        else torch.tensor(move_idxs, dtype=torch.int64)
    )
    if move_idxs_t.dtype != torch.int64:
        move_idxs_t = move_idxs_t.to(torch.int64)
    # Bounds check before device migration: stays on whatever device the
    # caller built move_idxs on. Realistic callers (random_scrambles inner
    # loop, beam-search children expansion) build on CPU — zero MPS sync.
    # MPS-pre-migrated input costs the same as before (no regression).
    if (move_idxs_t < 0).any() or (move_idxs_t >= spec.n_moves).any():
        raise ValueError(f"move index out of range [0, {spec.n_moves})")
    move_idxs_t = move_idxs_t.to(states.device)

    if move_idxs_t.dim() == 0:
        gathered = perm[move_idxs_t]  # (S,)
        if states.dim() == 1:
            return torch.gather(states, -1, gathered)
        # Broadcast a single move across a batch of states.
        gathered = gathered.unsqueeze(0).expand(states.shape[0], -1)
        return torch.gather(states, -1, gathered)

    if move_idxs_t.dim() == 1:
        if states.dim() != 2:
            raise ValueError(
                "1-d move_idxs requires 2-d states (B, S);"
                f" got states shape {tuple(states.shape)}"
            )
        if move_idxs_t.shape[0] != states.shape[0]:
            raise ValueError(
                f"move_idxs length {move_idxs_t.shape[0]} != batch"
                f" size {states.shape[0]}"
            )
        return torch.gather(states, -1, perm[move_idxs_t])

    raise ValueError(f"move_idxs must be 0-d or 1-d; got {move_idxs_t.dim()}-d")


def is_solved(states: torch.Tensor, spec: CubeSpec) -> torch.Tensor:
    """Return scalar bool for `(S,)` input, shape `(B,)` for `(B, S)`."""
    if states.shape[-1] != spec.n_stickers:
        raise ValueError(
            f"states last dim {states.shape[-1]} does not match"
            f" spec.n_stickers ({spec.n_stickers})"
        )
    target = spec.solved_state.to(device=states.device, dtype=states.dtype)
    if states.dim() == 1:
        return (states == target).all()
    return (states == target).all(dim=-1)


def apply_move_sequence(
    state: torch.Tensor, moves: Sequence[int], spec: CubeSpec
) -> torch.Tensor:
    """Apply a Python sequence of move indices to a single state, in order."""
    if state.dim() != 1:
        raise ValueError(
            f"apply_move_sequence expects a single state (1-d);"
            f" got shape {tuple(state.shape)}"
        )
    cur = state
    for m in moves:
        cur = apply_moves(cur, m, spec)
    return cur


def random_scrambles(
    spec: CubeSpec,
    batch_size: int,
    depth: int,
    generator: torch.Generator | None = None,
    prune_same_face: bool = True,
) -> tuple[torch.Tensor, torch.Tensor]:
    """Generate `batch_size` random scrambles of length `depth` from solved.

    Returns `(states, move_seqs)` with shapes `(B, n_stickers)` int8 and
    `(B, depth)` int64. When `prune_same_face=True` (default), consecutive
    moves on the same face are excluded — matches scramble-generation and
    beam-search conventions.
    """
    if batch_size < 0:
        raise ValueError(f"batch_size must be non-negative; got {batch_size}")
    if depth < 0:
        raise ValueError(f"depth must be non-negative; got {depth}")

    n_moves = spec.n_moves
    move_seqs = torch.empty((batch_size, depth), dtype=torch.int64)

    if depth > 0 and batch_size > 0:
        move_seqs[:, 0] = torch.randint(
            low=0, high=n_moves, size=(batch_size,), generator=generator
        )
        if not prune_same_face:
            for d in range(1, depth):
                move_seqs[:, d] = torch.randint(
                    low=0, high=n_moves, size=(batch_size,), generator=generator
                )
        else:
            face_idxs = torch.arange(n_moves) >> 1  # (n_moves,)
            for d in range(1, depth):
                prev_face = move_seqs[:, d - 1] >> 1  # (B,)
                # Per-row probability: 0 on same-face moves, uniform elsewhere.
                probs = (face_idxs.unsqueeze(0) != prev_face.unsqueeze(1)).to(
                    torch.float32
                )
                move_seqs[:, d] = torch.multinomial(
                    probs, num_samples=1, generator=generator
                ).squeeze(1)

    states = spec.solved_state.unsqueeze(0).expand(batch_size, -1).clone()
    for d in range(depth):
        states = apply_moves(states, move_seqs[:, d], spec)
    return states, move_seqs


def valid_next_moves_mask(
    prev_move_idxs: torch.Tensor | int | None, spec: CubeSpec
) -> torch.Tensor:
    """Bool mask over `spec.n_moves`. Same-face repeats relative to `prev` are False.

    `prev_move_idxs=None` -> shape `(n_moves,)` all True (no constraint).
    Scalar / 0-d prev -> shape `(n_moves,)`.
    1-d prev of shape `(B,)` -> shape `(B, n_moves)`.
    """
    n_moves = spec.n_moves
    if prev_move_idxs is None:
        return torch.ones(n_moves, dtype=torch.bool)
    prev_t = (
        prev_move_idxs
        if isinstance(prev_move_idxs, torch.Tensor)
        else torch.tensor(prev_move_idxs, dtype=torch.int64)
    )
    if prev_t.dtype != torch.int64:
        prev_t = prev_t.to(torch.int64)
    face_idxs = torch.arange(n_moves, device=prev_t.device) >> 1
    if prev_t.dim() == 0:
        return face_idxs != (prev_t >> 1)
    if prev_t.dim() == 1:
        return face_idxs.unsqueeze(0) != (prev_t >> 1).unsqueeze(1)
    raise ValueError(f"prev_move_idxs must be 0-d or 1-d; got {prev_t.dim()}-d")
