"""Fast tensor cube — production code path for env / training / search.

State is a flat sticker tensor of shape `(spec.n_stickers,)` (single) or
`(B, spec.n_stickers)` (batched), dtype `int8`. Move tables are static
sticker permutations snapshotted from the M1 / M8 oracle (see
`scripts/move_perm_from_oracle_2x2.py`,
`scripts/move_perm_from_oracle_3x3.py`); this module never imports the
oracle at runtime. Drift is caught by `test_move_perm_matches_oracle`
(2x2) and `test_move_perm_3x3_matches_oracle`.

Functions are device-agnostic and dtype-preserving — MPS tuning is M4.
"""

from collections.abc import Sequence

import torch

from rubik.cube.spec import CubeSpec

# Snapshot generated by scripts/move_perm_from_oracle_2x2.py.
# perm[move_idx, i] = source sticker position of slot i after the move.
# Apply via torch.gather(states, -1, perm[move_idxs]).
# Rows are one-line-per-move for scannability; line length is suppressed
# below (24 ints + comma+space don't fit in 88 cols and splitting hurts
# readability of the snapshot). Re-run the generator if any row changes.
# fmt: off
MOVE_PERM_2X2 = torch.tensor(
    (
        (2, 0, 3, 1, 8, 9, 6, 7, 12, 13, 10, 11, 16, 17, 14, 15, 4, 5, 18, 19, 20, 21, 22, 23),  # 0: U   # noqa: E501
        (1, 3, 0, 2, 16, 17, 6, 7, 4, 5, 10, 11, 8, 9, 14, 15, 12, 13, 18, 19, 20, 21, 22, 23),  # 1: U'  # noqa: E501
        (19, 1, 17, 3, 6, 4, 7, 5, 0, 9, 2, 11, 12, 13, 14, 15, 16, 22, 18, 20, 8, 21, 10, 23),  # 2: L   # noqa: E501
        (8, 1, 10, 3, 5, 7, 4, 6, 20, 9, 22, 11, 12, 13, 14, 15, 16, 2, 18, 0, 19, 21, 17, 23),  # 3: L'  # noqa: E501
        (0, 1, 7, 5, 4, 20, 6, 21, 10, 8, 11, 9, 2, 13, 3, 15, 16, 17, 18, 19, 14, 12, 22, 23),  # 4: F   # noqa: E501
        (0, 1, 12, 14, 4, 3, 6, 2, 9, 11, 8, 10, 21, 13, 20, 15, 16, 17, 18, 19, 5, 7, 22, 23),  # 5: F'  # noqa: E501
        (0, 9, 2, 11, 4, 5, 6, 7, 8, 21, 10, 23, 14, 12, 15, 13, 3, 17, 1, 19, 20, 18, 22, 16),  # 6: R   # noqa: E501
        (0, 18, 2, 16, 4, 5, 6, 7, 8, 1, 10, 3, 13, 15, 12, 14, 23, 17, 21, 19, 20, 9, 22, 11),  # 7: R'  # noqa: E501
        (13, 15, 2, 3, 1, 5, 0, 7, 8, 9, 10, 11, 12, 23, 14, 22, 18, 16, 19, 17, 20, 21, 4, 6),  # 8: B   # noqa: E501
        (6, 4, 2, 3, 22, 5, 23, 7, 8, 9, 10, 11, 12, 0, 14, 1, 17, 19, 16, 18, 20, 21, 15, 13),  # 9: B'  # noqa: E501
        (0, 1, 2, 3, 4, 5, 18, 19, 8, 9, 6, 7, 12, 13, 10, 11, 16, 17, 14, 15, 22, 20, 23, 21),  # 10: D  # noqa: E501
        (0, 1, 2, 3, 4, 5, 10, 11, 8, 9, 14, 15, 12, 13, 18, 19, 16, 17, 6, 7, 21, 23, 20, 22),  # 11: D' # noqa: E501
    ),
    dtype=torch.int64,
)
# fmt: on


# Snapshot generated by scripts/move_perm_from_oracle_3x3.py. Same shape /
# semantics as MOVE_PERM_2X2 — perm[move_idx, i] = source sticker position
# of slot i after the move; apply via torch.gather. Centers (within-face
# index 4 on each face → flat indices 4, 13, 22, 31, 40, 49) are fixed
# under all 12 QTM face turns.
# fmt: off
MOVE_PERM_3X3 = torch.tensor(
    (
        ( 6,  3,  0,  7,  4,  1,  8,  5,  2, 18, 19, 20, 12, 13, 14, 15, 16, 17, 27, 28, 29, 21, 22, 23, 24, 25, 26, 36, 37, 38, 30, 31, 32, 33, 34, 35,  9, 10, 11, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53),  #  0: U   # noqa: E501
        ( 2,  5,  8,  1,  4,  7,  0,  3,  6, 36, 37, 38, 12, 13, 14, 15, 16, 17,  9, 10, 11, 21, 22, 23, 24, 25, 26, 18, 19, 20, 30, 31, 32, 33, 34, 35, 27, 28, 29, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53),  #  1: U'  # noqa: E501
        (44,  1,  2, 41,  4,  5, 38,  7,  8, 15, 12,  9, 16, 13, 10, 17, 14, 11,  0, 19, 20,  3, 22, 23,  6, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 51, 39, 40, 48, 42, 43, 45, 18, 46, 47, 21, 49, 50, 24, 52, 53),  #  2: L   # noqa: E501
        (18,  1,  2, 21,  4,  5, 24,  7,  8, 11, 14, 17, 10, 13, 16,  9, 12, 15, 45, 19, 20, 48, 22, 23, 51, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37,  6, 39, 40,  3, 42, 43,  0, 44, 46, 47, 41, 49, 50, 38, 52, 53),  #  3: L'  # noqa: E501
        ( 0,  1,  2,  3,  4,  5, 17, 14, 11,  9, 10, 45, 12, 13, 46, 15, 16, 47, 24, 21, 18, 25, 22, 19, 26, 23, 20,  6, 28, 29,  7, 31, 32,  8, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 33, 30, 27, 48, 49, 50, 51, 52, 53),  #  4: F   # noqa: E501
        ( 0,  1,  2,  3,  4,  5, 27, 30, 33,  9, 10,  8, 12, 13,  7, 15, 16,  6, 20, 23, 26, 19, 22, 25, 18, 21, 24, 47, 28, 29, 46, 31, 32, 45, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 11, 14, 17, 48, 49, 50, 51, 52, 53),  #  5: F'  # noqa: E501
        ( 0,  1, 20,  3,  4, 23,  6,  7, 26,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 47, 21, 22, 50, 24, 25, 53, 33, 30, 27, 34, 31, 28, 35, 32, 29,  8, 37, 38,  5, 40, 41,  2, 43, 44, 45, 46, 42, 48, 49, 39, 51, 52, 36),  #  6: R   # noqa: E501
        ( 0,  1, 42,  3,  4, 39,  6,  7, 36,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,  2, 21, 22,  5, 24, 25,  8, 29, 32, 35, 28, 31, 34, 27, 30, 33, 53, 37, 38, 50, 40, 41, 47, 43, 44, 45, 46, 20, 48, 49, 23, 51, 52, 26),  #  7: R'  # noqa: E501
        (29, 32, 35,  3,  4,  5,  6,  7,  8,  2, 10, 11,  1, 13, 14,  0, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 53, 30, 31, 52, 33, 34, 51, 42, 39, 36, 43, 40, 37, 44, 41, 38, 45, 46, 47, 48, 49, 50,  9, 12, 15),  #  8: B   # noqa: E501
        (15, 12,  9,  3,  4,  5,  6,  7,  8, 51, 10, 11, 52, 13, 14, 53, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28,  0, 30, 31,  1, 33, 34,  2, 38, 41, 44, 37, 40, 43, 36, 39, 42, 45, 46, 47, 48, 49, 50, 35, 32, 29),  #  9: B'  # noqa: E501
        ( 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 42, 43, 44, 18, 19, 20, 21, 22, 23, 15, 16, 17, 27, 28, 29, 30, 31, 32, 24, 25, 26, 36, 37, 38, 39, 40, 41, 33, 34, 35, 51, 48, 45, 52, 49, 46, 53, 50, 47),  # 10: D   # noqa: E501
        ( 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 24, 25, 26, 18, 19, 20, 21, 22, 23, 33, 34, 35, 27, 28, 29, 30, 31, 32, 42, 43, 44, 36, 37, 38, 39, 40, 41, 15, 16, 17, 47, 50, 53, 46, 49, 52, 45, 48, 51),  # 11: D'  # noqa: E501
    ),
    dtype=torch.int64,
)
# fmt: on


# Keyed by spec.name so the 3x3 (M8) drops in alongside 2x2 with no
# code-path change. Adding a 4x4 / 5x5 / etc. is one new entry here.
_MOVE_PERM: dict[str, torch.Tensor] = {
    "2x2": MOVE_PERM_2X2,
    "3x3": MOVE_PERM_3X3,
}


def _perm_for(spec: CubeSpec) -> torch.Tensor:
    perm = _MOVE_PERM.get(spec.name)
    if perm is None:
        raise ValueError(f"no move-permutation table for spec {spec.name!r}")
    return perm


# Cache device-resident perm tables. Without this, apply_moves migrates
# the static (n_moves, n_stickers) int64 table from CPU to states.device
# on every call (an aten::_to_copy event of ~125-310 μs CPU dispatch for
# a 288-byte payload — pure overhead). At most ~4 entries total over the
# project's lifetime (2x2/3x3 × CPU/MPS). Entries are immutable from the
# caller's perspective (only read via gather), so no invalidation path.
_DEVICE_PERM_CACHE: dict[tuple[str, torch.device], torch.Tensor] = {}


def _perm_for_device(spec: CubeSpec, device: torch.device) -> torch.Tensor:
    key = (spec.name, device)
    cached = _DEVICE_PERM_CACHE.get(key)
    if cached is None:
        cached = _perm_for(spec).to(device)
        _DEVICE_PERM_CACHE[key] = cached
    return cached


def apply_moves(
    states: torch.Tensor, move_idxs: torch.Tensor | int, spec: CubeSpec
) -> torch.Tensor:
    """Apply moves to states; preserves device and dtype.

    `states` shape `(S,)` or `(B, S)`. `move_idxs` may be a Python int, a
    0-d tensor (broadcast across the batch / single state), or a 1-d
    tensor of length B (one move per row).
    """
    if states.shape[-1] != spec.n_stickers:
        raise ValueError(
            f"states last dim {states.shape[-1]} does not match"
            f" spec.n_stickers ({spec.n_stickers})"
        )
    perm = _perm_for_device(spec, states.device)

    move_idxs_t = (
        move_idxs
        if isinstance(move_idxs, torch.Tensor)
        else torch.tensor(move_idxs, dtype=torch.int64)
    )
    if move_idxs_t.dtype != torch.int64:
        move_idxs_t = move_idxs_t.to(torch.int64)
    # Bounds check before device migration: stays on whatever device the
    # caller built move_idxs on. Realistic callers (random_scrambles inner
    # loop, beam-search children expansion) build on CPU — zero MPS sync.
    # MPS-pre-migrated input costs the same as before (no regression).
    if (move_idxs_t < 0).any() or (move_idxs_t >= spec.n_moves).any():
        raise ValueError(f"move index out of range [0, {spec.n_moves})")
    move_idxs_t = move_idxs_t.to(states.device)

    if move_idxs_t.dim() == 0:
        gathered = perm[move_idxs_t]  # (S,)
        if states.dim() == 1:
            return torch.gather(states, -1, gathered)
        # Broadcast a single move across a batch of states.
        gathered = gathered.unsqueeze(0).expand(states.shape[0], -1)
        return torch.gather(states, -1, gathered)

    if move_idxs_t.dim() == 1:
        if states.dim() != 2:
            raise ValueError(
                "1-d move_idxs requires 2-d states (B, S);"
                f" got states shape {tuple(states.shape)}"
            )
        if move_idxs_t.shape[0] != states.shape[0]:
            raise ValueError(
                f"move_idxs length {move_idxs_t.shape[0]} != batch"
                f" size {states.shape[0]}"
            )
        return torch.gather(states, -1, perm[move_idxs_t])

    raise ValueError(f"move_idxs must be 0-d or 1-d; got {move_idxs_t.dim()}-d")


def apply_all_moves(states: torch.Tensor, spec: CubeSpec) -> torch.Tensor:
    """Apply every move in the move set to each state; preserves device + dtype.

    Used by DAVI (M5) for all-children expansion when computing the
    Bellman target, and by beam-search children expansion (M6).

    `states` shape `(S,)` or `(B, S)`. Output prepends a move axis:
    `(n_moves, S)` or `(B, n_moves, S)`. Equivalent to calling
    ``apply_moves(state, m, spec)`` for every `m`, but vectorized via a
    single fancy-index against the cached perm — no per-move dispatch.
    """
    if states.shape[-1] != spec.n_stickers:
        raise ValueError(
            f"states last dim {states.shape[-1]} does not match"
            f" spec.n_stickers ({spec.n_stickers})"
        )
    perm = _perm_for_device(spec, states.device)  # (n_moves, n_stickers)
    return states[..., perm]


def is_solved(states: torch.Tensor, spec: CubeSpec) -> torch.Tensor:
    """Return scalar bool for `(S,)` input, shape `(B,)` for `(B, S)`."""
    if states.shape[-1] != spec.n_stickers:
        raise ValueError(
            f"states last dim {states.shape[-1]} does not match"
            f" spec.n_stickers ({spec.n_stickers})"
        )
    target = spec.solved_state.to(device=states.device, dtype=states.dtype)
    if states.dim() == 1:
        return (states == target).all()
    return (states == target).all(dim=-1)


def apply_move_sequence(
    state: torch.Tensor, moves: Sequence[int], spec: CubeSpec
) -> torch.Tensor:
    """Apply a Python sequence of move indices to a single state, in order."""
    if state.dim() != 1:
        raise ValueError(
            f"apply_move_sequence expects a single state (1-d);"
            f" got shape {tuple(state.shape)}"
        )
    cur = state
    for m in moves:
        cur = apply_moves(cur, m, spec)
    return cur


def random_scrambles(
    spec: CubeSpec,
    batch_size: int,
    depth: int,
    generator: torch.Generator | None = None,
    prune_same_face: bool = True,
) -> tuple[torch.Tensor, torch.Tensor]:
    """Generate `batch_size` random scrambles of length `depth` from solved.

    Returns `(states, move_seqs)` with shapes `(B, n_stickers)` int8 and
    `(B, depth)` int64. When `prune_same_face=True` (default), consecutive
    moves on the same face are excluded — matches scramble-generation and
    beam-search conventions.
    """
    if batch_size < 0:
        raise ValueError(f"batch_size must be non-negative; got {batch_size}")
    if depth < 0:
        raise ValueError(f"depth must be non-negative; got {depth}")

    n_moves = spec.n_moves
    move_seqs = torch.empty((batch_size, depth), dtype=torch.int64)

    if depth > 0 and batch_size > 0:
        move_seqs[:, 0] = torch.randint(
            low=0, high=n_moves, size=(batch_size,), generator=generator
        )
        if not prune_same_face:
            for d in range(1, depth):
                move_seqs[:, d] = torch.randint(
                    low=0, high=n_moves, size=(batch_size,), generator=generator
                )
        else:
            face_idxs = torch.arange(n_moves) >> 1  # (n_moves,)
            for d in range(1, depth):
                prev_face = move_seqs[:, d - 1] >> 1  # (B,)
                # Per-row probability: 0 on same-face moves, uniform elsewhere.
                probs = (face_idxs.unsqueeze(0) != prev_face.unsqueeze(1)).to(
                    torch.float32
                )
                move_seqs[:, d] = torch.multinomial(
                    probs, num_samples=1, generator=generator
                ).squeeze(1)

    states = spec.solved_state.unsqueeze(0).expand(batch_size, -1).clone()
    for d in range(depth):
        states = apply_moves(states, move_seqs[:, d], spec)
    return states, move_seqs


def valid_next_moves_mask(
    prev_move_idxs: torch.Tensor | int | None, spec: CubeSpec
) -> torch.Tensor:
    """Bool mask over `spec.n_moves`. Same-face repeats relative to `prev` are False.

    `prev_move_idxs=None` -> shape `(n_moves,)` all True (no constraint).
    Scalar / 0-d prev -> shape `(n_moves,)`.
    1-d prev of shape `(B,)` -> shape `(B, n_moves)`.
    """
    n_moves = spec.n_moves
    if prev_move_idxs is None:
        return torch.ones(n_moves, dtype=torch.bool)
    prev_t = (
        prev_move_idxs
        if isinstance(prev_move_idxs, torch.Tensor)
        else torch.tensor(prev_move_idxs, dtype=torch.int64)
    )
    if prev_t.dtype != torch.int64:
        prev_t = prev_t.to(torch.int64)
    face_idxs = torch.arange(n_moves, device=prev_t.device) >> 1
    if prev_t.dim() == 0:
        return face_idxs != (prev_t >> 1)
    if prev_t.dim() == 1:
        return face_idxs.unsqueeze(0) != (prev_t >> 1).unsqueeze(1)
    raise ValueError(f"prev_move_idxs must be 0-d or 1-d; got {prev_t.dim()}-d")
